title: Gimeltra
description: No-nonsense simple transliteration between writing systems, mostly of Semitic origin
baseurl: "/gimeltra"
url: "https://twardoch.github.io"
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins: 
  - jekyll-include-cache
color_scheme: "white"
kramdown:
  parse_block_html: true
heading_anchors: true
collections:
  pages:
    output: true
    permalink: /:path/
permalink: pretty

footer_content: "[Github](https://github.com/twardoch/gimeltra)"

